theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
title: jim dolmas
description: >
  This is just a vehicle for sharing my research and some of my personal interests.
  You can email me at jim@jimdolmas.net.
logo: /assets/me2.jpg
author: Jim Dolmas
url: jimdolmas.net
twitter:
  username: jimdolmas
  card: summary
sidebar:
  nav: "research"
