theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
title: jim dolmas
description: >
  This is just a vehicle for sharing my research and some of my personal interests.
  You can email me at jim@jimdolmas.net.
logo: /assets/me2.jpg
author: Jim Dolmas

twitter:
  username: jimdolmas
  card: summary

analytics:
    provider: "google-universal"
  google:
    tracking_id: "UA-23474669-1"
