theme: jekyll-theme-minimal
title: jim dolmas's homepage
description: This is just a vehicle for sharing my research and some of my personal interests.
logo: /assets/me.jpg
sidebar:
  nav: "research"
