theme: jekyll-theme-minimal
title: jim dolmas's website
description: >
  This is just a vehicle for sharing my research and some of my personal interests.
  You can email me at jim@jimdolmas.net.
logo: /assets/me.jpg
sidebar:
  nav: "research"
